name: atta-detection
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - python=3.12.1
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - filelock==3.13.1
    - fsspec==2023.12.2
    - huggingface-hub==0.20.3
    - idna==3.6
    - numpy==1.26.3
    - packaging==23.2
    - pip==23.3.1
    - pyyaml==6.0.1
    - regex==2023.12.25
    - requests==2.31.0
    - safetensors==0.4.2
    - setuptools==68.2.2
    - tokenizers==0.15.1
    - tqdm==4.66.1
    - transformers==4.37.1
    - typing-extensions==4.9.0
    - urllib3==2.1.0
    - wheel==0.41.2
